sudo: false
language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - "pypy"

env:
  - PYTHONIOENCODING=utf-8

install:
    - pip install -U tornado

before_script:
    - "mysql -e 'create database test_pymysql  DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'"
    - "mysql -e 'create database test_pymysql2 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'"
    - cp .travis.databases.json tornado_mysql/tests/databases.json

script: ./runtests.py
