# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=30)),
                ('actor_movie', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=20)),
                ('movie_logo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=50)),
                ('song_name', models.CharField(max_length=200)),
                ('movieName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.movie')),
            ],
        ),
    ]
