# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
