# Generated by Django 3.2.6 on 2021-08-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_subscription_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='allow_external',
            field=models.BooleanField(default=False),
        ),
    ]
