# Generated by Django 3.2.6 on 2021-08-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0005_subscription_allow_crud_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='type',
            field=models.CharField(default='manager', max_length=50, null=True),
        ),
    ]
