# Generated by Django 3.2.6 on 2021-08-12 17:06

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banks',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 17, 6, 11, 611112)),
        ),
        migrations.AddField(
            model_name='customers',
            name='uid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 17, 6, 11, 611505)),
        ),
        migrations.AddField(
            model_name='loans',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 17, 6, 11, 611984)),
        ),
        migrations.AlterField(
            model_name='banks',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='banks',
            name='uid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='uid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='query_log',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 17, 6, 11, 612387)),
        ),
    ]
