# Generated by Django 3.2.6 on 2021-08-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_manager', '0002_auto_20210812_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='when',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='when',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='when',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='query_log',
            name='when',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
