# Generated by Django 3.2.6 on 2021-08-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_manager', '0003_auto_20210812_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loans',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='query_log',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
