# Generated by Django 3.2.6 on 2021-08-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_manager', '0006_alter_loans_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loans',
            name='emi_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loans',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loans',
            name='period',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loans',
            name='period_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loans',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loans',
            name='repaid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loans',
            name='total_amount_PI',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
