# Generated by Django 3.2.6 on 2021-08-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_manager', '0007_auto_20210813_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loans',
            old_name='period_months',
            new_name='emi_months',
        ),
        migrations.AddField(
            model_name='loans',
            name='emi_months_repaid',
            field=models.IntegerField(default=0),
        ),
    ]
