# Generated by Django 3.2.6 on 2021-08-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_manager', '0008_auto_20210813_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loans',
            old_name='total_amount_PI',
            new_name='total_amount_pi',
        ),
    ]
