# Generated by Django 3.2.6 on 2021-08-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_manager', '0009_rename_total_amount_pi_loans_total_amount_pi'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
