# Generated by Django 3.2.6 on 2021-08-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_manager', '0010_loans_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_log',
            name='type',
            field=models.CharField(max_length=150),
        ),
    ]
